import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // 👉 এই অংশটা নতুন করে যোগ করা হলো
  other: {
    'google-site-verification': 'Y25R2H8ZXaJDHU82-W_6dguROUmmpVZjRkzCJND7BSs',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* যেকোনো কারণে metadata কাজ না করলে সরাসরি head-tag এ fallback */}
        <meta name="google-site-verification" content="Y25R2H8ZXaJDHU82-W_6dguROUmmpVZjRkzCJND7BSs" />
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
